name: mlmd_env_39_26.1.3
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - altair=5.5.0=pyhd8ed1ab_1
  - ase=3.23.0=pyhd8ed1ab_0
  - attrs=25.3.0=pyh71513ae_0
  - aws-c-auth=0.9.3=h2970c50_0
  - aws-c-cal=0.9.13=h46f3b43_1
  - aws-c-common=0.12.6=hfd05255_0
  - aws-c-compression=0.3.1=hcb3a2da_9
  - aws-c-event-stream=0.5.7=ha388e84_1
  - aws-c-http=0.10.7=hc678f4a_5
  - aws-c-io=0.23.3=h0d5b9f9_5
  - aws-c-mqtt=0.13.3=hfa314fa_11
  - aws-c-s3=0.11.3=ha659bf3_1
  - aws-c-sdkutils=0.2.4=hcb3a2da_4
  - aws-checksums=0.2.7=hcb3a2da_5
  - aws-crt-cpp=0.35.4=hca034e6_0
  - aws-sdk-cpp=1.11.606=hac16450_10
  - blinker=1.9.0=pyhff2d567_0
  - brotli=1.2.0=h2d644bc_1
  - brotli-bin=1.2.0=hfd05255_1
  - brotli-python=1.0.9=py39h99910a6_8
  - bzip2=1.0.8=h2bbff1b_6
  - c-ares=1.34.6=hfd05255_0
  - ca-certificates=2025.12.2=haa95532_0
  - cachetools=6.1.0=pyhd8ed1ab_0
  - certifi=2025.10.5=py39haa95532_0
  - cffi=1.17.1=py39ha55e580_0
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - click=8.1.8=pyh7428d3b_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.0=py39h2b77a98_2
  - cryptography=44.0.1=py39hbd6ee87_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - dnspython=2.7.0=pyhff2d567_1
  - expat=2.7.3=h885b0b7_4
  - flask=3.1.2=pyhd8ed1ab_0
  - fonttools=4.59.1=py39h5769e4c_0
  - freetype=2.14.1=h57928b3_0
  - future=1.0.0=pyhd8ed1ab_2
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.45=pyhff2d567_0
  - glib=2.84.4=h60240c0_0
  - glib-tools=2.84.4=h3823947_0
  - gst-plugins-base=1.24.11=h3fe0a9e_0
  - gstreamer=1.24.11=h233a61a_0
  - h2=4.2.0=pyhd8ed1ab_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he0c23c2_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - itsdangerous=2.2.0=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.1=pyhd8ed1ab_0
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.4.1=pyh29332c3_0
  - kiwisolver=1.4.7=py39h2b77a98_0
  - krb5=1.21.3=hdf4eb48_0
  - latexcodec=2.0.1=pyh9f0ad1d_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libabseil=20250512.1=cxx17_habfad5f_0
  - libarrow=21.0.0=h5f2f476_14_cuda
  - libarrow-acero=21.0.0=h7d8d6a5_14_cuda
  - libarrow-compute=21.0.0=h2db994a_14_cuda
  - libarrow-dataset=21.0.0=h7d8d6a5_14_cuda
  - libarrow-substrait=21.0.0=hf865cc0_14_cuda
  - libblas=3.11.0=5_hf2e6a31_mkl
  - libbrotlicommon=1.2.0=hfd05255_1
  - libbrotlidec=1.2.0=hfd05255_1
  - libbrotlienc=1.2.0=hfd05255_1
  - libcblas=3.11.0=5_h2a3cdd5_mkl
  - libclang13=21.1.7=default_ha2db4b5_3
  - libcrc32c=1.1.2=h0e60522_0
  - libcurl=8.17.0=h43ecb02_1
  - libdeflate=1.22=h2466b09_0
  - libevent=2.1.12=h3671451_1
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h8ee18e1_16
  - libglib=2.84.4=hfaec014_0
  - libgomp=15.2.0=h8ee18e1_16
  - libgoogle-cloud=2.39.0=h19ee442_0
  - libgoogle-cloud-storage=2.39.0=he04ea4c_0
  - libgrpc=1.73.1=h317e13b_1
  - libhwloc=2.12.1=default_h88281d1_1000
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.2=hfd05255_0
  - liblapack=3.11.0=5_hf9ab0e9_mkl
  - libogg=1.3.5=h2466b09_1
  - libparquet=21.0.0=h7051d1f_14_cuda
  - libpng=1.6.53=h7351971_0
  - libprotobuf=6.31.1=hdcda5b4_4
  - libre2-11=2025.11.05=h0eb2380_0
  - libsqlite=3.51.1=hf5d6505_1
  - libssh2=1.11.1=h9aa295b_0
  - libthrift=0.22.0=h23985f6_1
  - libtiff=4.7.0=hfc51747_1
  - libutf8proc=2.11.2=hb980946_0
  - libvorbis=1.3.7=h5112557_2
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.13.9=h741aa76_0
  - libzlib=1.3.1=h02ab6af_0
  - llvm-openmp=21.1.8=h4fa8253_0
  - llvmlite=0.43.0=py39he94c479_1
  - lz4-c=1.10.0=h2466b09_1
  - markupsafe=3.0.2=py39hf73967f_1
  - matminer=0.9.3=pyhd8ed1ab_1
  - matplotlib=3.7.3=py39hcbf5309_0
  - matplotlib-base=3.7.3=py39hf19769e_0
  - mkl=2025.3.0=hac47afa_454
  - monty=2024.12.10=pyhd8ed1ab_0
  - mpmath=1.3.0=pyhd8ed1ab_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - narwhals=2.1.2=pyhe01879c_0
  - networkx=3.2.1=pyhd8ed1ab_0
  - numba=0.60.0=py39h5dcb127_0
  - numpy=1.25.2=py39h816b6a6_0
  - openjpeg=2.5.3=h24db6dd_1
  - openssl=3.6.0=h725018a_0
  - orc=2.2.1=h7414dfc_0
  - packaging=25.0=pyh29332c3_1
  - palettable=3.3.3=pyhd8ed1ab_1
  - pandas=1.5.3=py39h2ba5b7c_1
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.46=h3402e2f_0
  - pillow=11.3.0=py39hbad85af_0
  - pip=25.3=pyhc872135_0
  - plotly=6.3.0=pyhd8ed1ab_0
  - ply=3.11=pyhd8ed1ab_3
  - protobuf=6.31.1=py39h9bd55df_0
  - pthread-stubs=0.4=h0e40799_1002
  - pyarrow=21.0.0=py39hcbf5309_0
  - pyarrow-core=21.0.0=py39hd24caa1_0_cuda
  - pybtex=0.25.1=pyhd8ed1ab_0
  - pycparser=2.22=pyh29332c3_1
  - pydeck=0.9.1=pyhd8ed1ab_0
  - pymatgen=2024.5.31=py39h941ed31_0
  - pymongo=4.13.2=py39hdb6649d_0
  - pyopenssl=25.0.0=py39hb6ff9d5_0
  - pyparsing=3.2.3=pyhe01879c_2
  - pyqt=5.15.11=py39he15501f_1
  - pyqt5-sip=12.17.0=py39ha51f57c_1
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.9.25=h716150d_1
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.9=2_cp39
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py39hf73967f_2
  - qt-main=5.15.15=hb098fff_5
  - re2=2025.11.05=ha104f34_0
  - referencing=0.36.2=pyh29332c3_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rpds-py=0.27.0=py39hcab59ba_0
  - ruamel.yaml=0.18.15=py39h0802e32_0
  - ruamel.yaml.clib=0.2.8=py39ha55e580_1
  - scienceplots=2.1.1=pyhd8ed1ab_1
  - scikit-learn=1.6.1=py39hdd013cc_0
  - scipy=1.11.4=py39hddb5d58_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=80.9.0=py39haa95532_0
  - shap=0.42.1=py39h1679cfb_0
  - sip=6.10.0=py39ha51f57c_0
  - six=1.17.0=pyhe01879c_1
  - slicer=0.0.7=pyhd8ed1ab_0
  - smmap=5.0.2=pyhd8ed1ab_0
  - snappy=1.2.2=h7fa0ca8_1
  - sniffio=1.3.1=pyhd8ed1ab_1
  - spglib=2.6.0=py39h2b0bdfa_0
  - sqlite=3.51.0=hda9a48d_0
  - statsmodels=0.14.5=py39h9e4d2f2_0
  - streamlit=1.48.1=pyhd8ed1ab_0
  - sympy=1.14.0=pyh04b8f61_5
  - tabulate=0.9.0=pyhd8ed1ab_2
  - tbb=2022.3.0=hd094cb3_1
  - tenacity=9.1.2=pyhd8ed1ab_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.15=hf199647_0
  - toml=0.10.2=pyhd8ed1ab_1
  - tomli=2.2.1=pyhe01879c_2
  - tornado=6.5.2=py39h0802e32_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typing_extensions=4.14.1=pyhe01879c_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - uncertainties=3.2.3=pyhd8ed1ab_0
  - unicodedata2=16.0.0=py39ha55e580_0
  - urllib3=1.26.19=py39haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - watchdog=6.0.0=py39hcbf5309_0
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - wheel=0.45.1=py39haa95532_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - xorg-libxau=1.0.12=hba3369d_1
  - xorg-libxdmcp=1.1.5=hba3369d_1
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=h6a83c73_3
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h02ab6af_0
  - zstandard=0.23.0=py39h0802e32_3
  - zstd=1.5.7=h534d264_6
  - pip:
      - altex==0.2.0
      - annotated-types==0.7.0
      - anyio==4.12.0
      - asn1crypto==1.5.1
      - boto3==1.42.21
      - botocore==1.42.21
      - distro==1.9.0
      - exceptiongroup==1.3.1
      - favicon==0.7.0
      - filelock==3.19.1
      - h11==0.16.0
      - htbuilder==0.9.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - jiter==0.12.0
      - jmespath==1.0.1
      - markdown==3.9
      - markdownlit==0.0.7
      - openai==2.14.0
      - platformdirs==4.4.0
      - prometheus-client==0.23.1
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pyjwt==2.10.1
      - pymdown-extensions==10.20
      - s3transfer==0.16.0
      - snowflake-connector-python==4.1.1
      - snowflake-snowpark-python==1.44.0
      - sortedcontainers==2.4.0
      - st-theme==1.2.3
      - streamlit-avatar==0.1.3
      - streamlit-camera-input-live==0.2.0
      - streamlit-card==1.0.2
      - streamlit-embedcode==0.1.2
      - streamlit-extras==0.7.8
      - streamlit-faker==0.0.4
      - streamlit-image-coordinates==0.2.2
      - streamlit-keyup==0.3.0
      - streamlit-notify==0.3.1
      - streamlit-option-menu==0.4.0
      - streamlit-shap==1.0.2
      - streamlit-toggle-switch==1.0.2
      - streamlit-vertical-slider==2.5.5
      - tomlkit==0.13.3
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzlocal==5.3.1
      - validators==0.35.0
prefix: G:\anaconda\envs\mlmd_env_39_26.1.3
